// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSettings(arg1:number):Promise<void>;

export function GetLocalIP():Promise<string>;

export function GetNetStats():Promise<main.NetStats>;

export function GetPing():Promise<string>;

export function GetStartup():Promise<boolean>;

export function OpenSettings():Promise<void>;

export function SetStartup(arg1:boolean):Promise<boolean>;
