// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSettings(arg1) {
  return window['go']['main']['App']['CloseSettings'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetNetStats() {
  return window['go']['main']['App']['GetNetStats']();
}

export function GetPing() {
  return window['go']['main']['App']['GetPing']();
}

export function GetStartup() {
  return window['go']['main']['App']['GetStartup']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function SetStartup(arg1) {
  return window['go']['main']['App']['SetStartup'](arg1);
}
